language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt

before_script:
  - export FLASK_APP=app.py
script:
  - ls -al
after_success:
  - echo "Sukses .."
after_failure:
  - echo "Gagal .."
after_script:
  - echo "Membersihkan .."
# script: python -m pytest -v

# script: flask test